apiVersion: v1
kind: Service
metadata:
  name: wechat-observatory
  namespace: wechat-observatory
spec:
  selector:
    app: wechat-observatory
  ports:
    - name: http
      port: 8088
      targetPort: 8088
